version: '3'

services:
  mysql_db:
    image: mysql:8.0.41
    environment:
      MYSQL_ROOT_PASSWORD: 'Shivam@123'
      MYSQL_DATABASE: 'fidelity'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: stock_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    environment:
      - DATABASE_HOST=mysql_db  # Update to match the service name
      - DATABASE_PORT=3306
      - DATABASE_NAME=fidelity
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Shivam@123

volumes:
  db_data: