# Generated by Django 5.1.6 on 2025-02-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_rename_user_employee_username_employee_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='0000000000', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
