# Generated by Django 5.1.6 on 2025-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ordId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('price', models.FileField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('addr', models.CharField(max_length=100)),
            ],
        ),
    ]
