# Generated by Django 5.1.6 on 2025-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_app', '0002_alter_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
